import { TeamMember, Technology, Offering } from "./type";

export const MISSION_FEATURES: string[] = [
  "Structured, secure vulnerability reporting",
  "Transparent evaluation & merit-based rewards",
  "Anti-cheating and plagiarism prevention",
  "Innovation through real-world challenges",
];

export const VISION_FEATURES: string[] = [
  "Globally trusted platform for all stakeholders",
  "Active, security-first collaborative community",
  "Scalable infrastructure for enterprise bounties",
  "Cybersecurity education through practice",
];

export const SUPERVISORS: TeamMember[] = [
  {
    name: "Sreng Chipor",
    badge: "Mentor",
    badgeColor: "pink",
    subRole: "Supervisor",
    quote: '"Guiding the next generation of cybersecurity experts."',
    image: "/teams/Teacher Sreng Chipor.png",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    email: "chipor@devsolve.io",
  },
  {
    name: "Rin Bunvarn",
    badge: "Mentor",
    badgeColor: "pink",
    subRole: "Supervisor",
    quote: '"Building resilient systems through rigorous academic foundation."',
    image: "/teams/Teacher Rin Bunvarn.jpg",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    email: "bunvarn@devsolve.io",
  },
];

export const STUDENT_DEVELOPERS: TeamMember[] = [
  {
    name: "Taing Sengkim",
    badge: "Leader",
    badgeColor: "purple",
    subRole: "Full Stack",
    quote: '"Visionary leadership drives technical success."',
    image: "/teams/Taing Sengkim.jpg",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    telegram: "https://t.me",
  },
  {
    name: "Lor Vengroth",
    badge: "Sub Leader",
    badgeColor: "purple",
    subRole: "Full Stack",
    quote: '"Architecting the backbone of security."',
    image: "/teams/Lor Vengroth.JPG",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    telegram: "https://t.me",
  },
  {
    name: "San Tol",
    badge: "Member",
    badgeColor: "blue",
    subRole: "Full Stack",
    quote: '"Visualizing threats for better protection."',
    image: "/teams/San Tol.jpg",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    telegram: "https://t.me",
  },
  {
    name: "Ky Reaksa",
    badge: "Member",
    badgeColor: "blue",
    subRole: "Full Stack",
    quote: '"Innovation through collaborative logic."',
    image: "/teams/Ky Reaksa.JPG",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    telegram: "https://t.me",
  },
  {
    name: "Chamreun Molikatevy",
    badge: "Member",
    badgeColor: "blue",
    subRole: "Full Stack",
    quote: '"Crafting pixel-perfect secure experiences."',
    image: "/teams/Chamreun Molikatevy.JPG",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    telegram: "https://t.me",
  },
  {
    name: "Dim Pathea",
    badge: "Member",
    badgeColor: "blue",
    subRole: "Full Stack",
    quote: '"Design with security in mind from day one."',
    image: "/teams/Dim Pathea.JPG",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    telegram: "https://t.me",
  },
  {
    name: "Tollah Hamadabidin",
    badge: "Member",
    badgeColor: "blue",
    subRole: "Full Stack",
    quote: '"Robust code is the best defense."',
    image: "/teams/Tollah Hamadabidin.jpg",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    telegram: "https://t.me",
  },
  {
    name: "Bun Raksa",
    badge: "Member",
    badgeColor: "blue",
    subRole: "Full Stack",
    quote: '"Securing the future, one line of code at a time."',
    image: "/teams/Bun Raksa.JPG",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    telegram: "https://t.me",
  },
  {
    name: "Seu Narong",
    badge: "Member",
    badgeColor: "blue",
    subRole: "Full Stack",
    quote: '"Innovation through collaborative logic."',
    image: "/teams/Seu Narong.jpg",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    telegram: "https://t.me",
  },
];

export const TECHNOLOGIES: Technology[] = [
  {
    name: "Next.js",
    description: "App Router frontend and the server proxy layer",
    iconName: "Triangle",
  },
  {
    name: "Spring Boot",
    description: "Backend API and business logic",
    iconName: "Leaf",
  },
  {
    name: "PostgreSQL",
    description: "Primary relational datastore",
    iconName: "Database",
  },
  {
    name: "Redis",
    description: "Caching and session storage",
    iconName: "Zap",
  },
  {
    name: "MinIO",
    description: "S3-compatible object storage",
    iconName: "HardDrive",
  },
  {
    name: "Meilisearch",
    description: "Full-text search across the platform",
    iconName: "Search",
  },
  {
    name: "Keycloak",
    description: "OIDC single sign-on with PKCE",
    iconName: "KeyRound",
  },
  {
    name: "VirusTotal",
    description: "Malware scanning on every upload",
    iconName: "ShieldAlert",
  },
  {
    name: "Reverse proxy",
    description: "TLS termination and request routing",
    iconName: "Waypoints",
  },
];

export const OFFERINGS: Offering[] = [
  {
    iconName: "Code",
    title: "Technical Challenges",
    description: "Real-world coding and engineering challenges with secure evaluation and confidential judging.",
    accentBg: "bg-blue-50",
    accentText: "text-blue-600",
    borderColor: "border-blue-100 hover:border-blue-200",
  },
  {
    iconName: "Bug",
    title: "Bounty Programs",
    description: "Scoped organization programs for identifying, documenting, and resolving technical vulnerabilities.",
    accentBg: "bg-red-50",
    accentText: "text-red-500",
    borderColor: "border-red-100 hover:border-red-200",
  },
  {
    iconName: "MessageSquare",
    title: "Discussion",
    description: "An integrated community forum to exchange technical insights, ask questions, and share knowledge.",
    accentBg: "bg-purple-50",
    accentText: "text-purple-600",
    borderColor: "border-purple-100 hover:border-purple-200",
  },
];
