import type {
  PriorityReviewItem,
  ReviewQueueLane,
} from "@/components/report-management/review-queue/types";

export const REVIEW_QUEUE_LANES: ReviewQueueLane[] = [
  {
    title: "Pending Intake",
    count: 20,
    description: "New submissions waiting for first-pass moderation and scope validation.",
    accent: "amber",
  },
  {
    title: "Under Review",
    count: 5,
    description: "Analysts are checking evidence quality, impact, and report completeness.",
    accent: "blue",
  },
  {
    title: "Approval Ready",
    count: 8,
    description: "Reports cleared for final sign-off, payout confirmation, or closure.",
    accent: "emerald",
  },
];

export const PRIORITY_REVIEW_ITEMS: PriorityReviewItem[] = [
  {
    id: 1,
    reportId: "RPT-001",
    title: "TikTok Security Bug Bounty",
    severity: "Critical",
    reporter: "Seng Songhuor",
    submittedAt: "Jul 29, 2026, 04:30:15 PM",
    queue: "Pending Intake",
    status: "Needs scope validation",
    assets: ["api.tiktok.com", "Android App"],
    reportType: "Bounty",
    authorInitials: "SS",
  },
  {
    id: 6,
    reportId: "RPT-006",
    title: "TikTok Mobile App Token Exchange",
    severity: "Critical",
    reporter: "Seng Songhuor",
    submittedAt: "Jul 28, 2026, 02:14:28 PM",
    queue: "Under Review",
    status: "Awaiting severity confirmation",
    assets: ["Android App", "auth.tiktok.com"],
    reportType: "Bounty",
    authorInitials: "SS",
  },
  {
    id: 9,
    reportId: "RPT-009",
    title: "TikTok Public API Partner Sandbox",
    severity: "High",
    reporter: "Seng Songhuor",
    submittedAt: "Jul 28, 2026, 11:45:50 AM",
    queue: "Under Review",
    status: "Evidence review in progress",
    assets: ["sandbox-api.tiktok.com", "Partner Sandbox"],
    reportType: "Bounty",
    authorInitials: "SS",
  },
  {
    id: 3,
    reportId: "RPT-003",
    title: "TikTok Creator Commerce APIs",
    severity: "Medium",
    reporter: "Seng Songhuor",
    submittedAt: "Jul 27, 2026, 09:20:41 AM",
    queue: "Approval Ready",
    status: "Waiting analyst notes",
    assets: ["commerce-api.tiktok.com", "Partner Portal"],
    reportType: "Bounty",
    authorInitials: "SS",
  },
];
