import type { DiagramTemplate } from "./types";

export const DIAGRAM_TEMPLATES: DiagramTemplate[] = [
  {
    id: "concept-ddd",
    name: "DDD Concept & Bounded Contexts",
    category: "concept",
    description: "Domain-Driven Design conceptual architecture with Bounded Contexts & Aggregate Roots",
    nodes: [
      {
        id: "ctx-auth",
        type: "groupNode",
        position: { x: 40, y: 40 },
        data: {
          label: "Identity & Access Context",
          groupTitle: "Identity & Access Context",
          subtext: "Authentication & User Management boundary",
          badge: "BOUNDED CONTEXT",
          borderStyle: "dashed",
        },
      },
      {
        id: "concept-user-agg",
        type: "conceptNode",
        position: { x: 70, y: 110 },
        data: {
          label: "User Aggregate",
          subtext: "Root entity holding credentials, profile, and roles",
          badge: "AGGREGATE ROOT",
          colorTheme: "blue",
        },
      },
      {
        id: "concept-session-vo",
        type: "conceptNode",
        position: { x: 70, y: 260 },
        data: {
          label: "Session Token",
          subtext: "Immutable OIDC JWT principal and claims",
          badge: "VALUE OBJECT",
          colorTheme: "indigo",
        },
      },
      {
        id: "ctx-order",
        type: "groupNode",
        position: { x: 400, y: 40 },
        data: {
          label: "Order & Checkout Context",
          groupTitle: "Order & Checkout Context",
          subtext: "Transaction processing and fulfillment lifecycle",
          badge: "CORE DOMAIN",
          borderStyle: "solid",
        },
      },
      {
        id: "concept-order-agg",
        type: "conceptNode",
        position: { x: 430, y: 110 },
        data: {
          label: "Order Aggregate Root",
          subtext: "Coordinates order status, line items, and payment state",
          badge: "AGGREGATE ROOT",
          colorTheme: "emerald",
        },
      },
      {
        id: "concept-payment-vo",
        type: "conceptNode",
        position: { x: 430, y: 260 },
        data: {
          label: "Payment Intent",
          subtext: "Stripe/Gateway transactional reference",
          badge: "VALUE OBJECT",
          colorTheme: "purple",
        },
      },
      {
        id: "ctx-catalog",
        type: "groupNode",
        position: { x: 760, y: 40 },
        data: {
          label: "Inventory & Catalog Context",
          groupTitle: "Inventory & Catalog Context",
          subtext: "Product catalog and stock management",
          badge: "SUPPORTING DOMAIN",
          borderStyle: "dashed",
        },
      },
      {
        id: "concept-product-agg",
        type: "conceptNode",
        position: { x: 790, y: 110 },
        data: {
          label: "Product Entity",
          subtext: "SKU, pricing model, variants, and descriptions",
          badge: "ENTITY",
          colorTheme: "amber",
        },
      },
      {
        id: "concept-stock-vo",
        type: "conceptNode",
        position: { x: 790, y: 260 },
        data: {
          label: "Stock Allocation",
          subtext: "Warehouse inventory reservation lock",
          badge: "DOMAIN SERVICE",
          colorTheme: "cyan",
        },
      },
    ],
    edges: [
      {
        id: "e-user-session",
        source: "concept-user-agg",
        target: "concept-session-vo",
        label: "issues principal",
        animated: false,
      },
      {
        id: "e-user-order",
        source: "concept-user-agg",
        target: "concept-order-agg",
        label: "places order (Customer ID)",
        animated: true,
      },
      {
        id: "e-order-payment",
        source: "concept-order-agg",
        target: "concept-payment-vo",
        label: "captures payment",
        animated: false,
      },
      {
        id: "e-order-product",
        source: "concept-order-agg",
        target: "concept-product-agg",
        label: "references SKU",
        animated: false,
      },
      {
        id: "e-product-stock",
        source: "concept-product-agg",
        target: "concept-stock-vo",
        label: "reserves inventory",
        animated: false,
      },
    ],
  },

  {
    id: "flow-checkout",
    name: "User Checkout Flowchart",
    category: "flowchart",
    description: "Step-by-step process flow with decisions, event triggers, and documents",
    nodes: [
      {
        id: "flow-start",
        type: "terminalNode",
        position: { x: 50, y: 180 },
        data: {
          label: "Start Checkout",
          terminalType: "start",
        },
      },
      {
        id: "flow-action-cart",
        type: "actionNode",
        position: { x: 260, y: 165 },
        data: {
          label: "Review Shopping Cart",
          actor: "Customer",
          subtext: "Verify quantities and items",
        },
      },
      {
        id: "flow-decision-promo",
        type: "decisionNode",
        position: { x: 520, y: 165 },
        data: {
          label: "Apply promo discount?",
          badge: "Promo Check",
        },
      },
      {
        id: "flow-event-stripe",
        type: "eventNode",
        position: { x: 760, y: 80 },
        data: {
          label: "Stripe Webhook Received",
          triggerType: "webhook",
        },
      },
      {
        id: "flow-action-pay",
        type: "actionNode",
        position: { x: 760, y: 220 },
        data: {
          label: "Authorize Payment Card",
          actor: "Payment Gateway",
          subtext: "3D Secure verification",
        },
      },
      {
        id: "flow-data-invoice",
        type: "dataNode",
        position: { x: 1040, y: 130 },
        data: {
          label: "Order Invoice PDF",
          badge: "DOCUMENT",
          subtext: "Generated JSON payload & receipt",
        },
      },
      {
        id: "flow-end",
        type: "terminalNode",
        position: { x: 1060, y: 260 },
        data: {
          label: "Order Fulfilled",
          terminalType: "end",
        },
      },
    ],
    edges: [
      {
        id: "ef-1",
        source: "flow-start",
        target: "flow-action-cart",
        animated: true,
      },
      {
        id: "ef-2",
        source: "flow-action-cart",
        target: "flow-decision-promo",
      },
      {
        id: "ef-3",
        source: "flow-decision-promo",
        target: "flow-action-pay",
        label: "Proceed to Payment",
        animated: true,
      },
      {
        id: "ef-4",
        source: "flow-event-stripe",
        target: "flow-action-pay",
        label: "Charge Succeeded",
      },
      {
        id: "ef-5",
        source: "flow-action-pay",
        target: "flow-data-invoice",
        label: "Generate Receipt",
      },
      {
        id: "ef-6",
        source: "flow-action-pay",
        target: "flow-end",
        label: "Success",
        animated: true,
      },
    ],
  },

  {
    id: "uml-ecommerce",
    name: "UML Class Architecture",
    category: "uml",
    description: "Object-oriented class structures, interfaces, fields, and method contracts",
    nodes: [
      {
        id: "uml-orderable",
        type: "classNode",
        position: { x: 60, y: 60 },
        data: {
          label: "Orderable",
          isInterface: true,
          attributes: [
            { id: "a1", visibility: "+", name: "id", type: "UUID" },
            { id: "a2", visibility: "+", name: "unitPrice", type: "BigDecimal" },
          ],
          methods: [
            { id: "m1", visibility: "+", name: "calculateTax()", type: "BigDecimal" },
            { id: "m2", visibility: "+", name: "getSKU()", type: "String" },
          ],
        },
      },
      {
        id: "uml-product",
        type: "classNode",
        position: { x: 60, y: 280 },
        data: {
          label: "Product",
          attributes: [
            { id: "ap1", visibility: "-", name: "sku", type: "String" },
            { id: "ap2", visibility: "-", name: "stock", type: "int" },
            { id: "ap3", visibility: "+", name: "title", type: "String" },
          ],
          methods: [
            { id: "mp1", visibility: "+", name: "reserveStock(qty)", type: "boolean" },
            { id: "mp2", visibility: "+", name: "applyDiscount(pct)", type: "void" },
          ],
        },
      },
      {
        id: "uml-order",
        type: "classNode",
        position: { x: 420, y: 150 },
        data: {
          label: "Order",
          attributes: [
            { id: "ao1", visibility: "-", name: "orderId", type: "UUID" },
            { id: "ao2", visibility: "-", name: "status", type: "OrderStatus" },
            { id: "ao3", visibility: "+", name: "items", type: "List<OrderItem>" },
          ],
          methods: [
            { id: "mo1", visibility: "+", name: "addItem(product, qty)", type: "void" },
            { id: "mo2", visibility: "+", name: "calculateTotal()", type: "BigDecimal" },
            { id: "mo3", visibility: "+", name: "checkout(gateway)", type: "PaymentResult" },
          ],
        },
      },
      {
        id: "uml-customer",
        type: "classNode",
        position: { x: 780, y: 150 },
        data: {
          label: "Customer",
          attributes: [
            { id: "ac1", visibility: "-", name: "customerId", type: "UUID" },
            { id: "ac2", visibility: "+", name: "email", type: "String" },
            { id: "ac3", visibility: "-", name: "tier", type: "LoyaltyTier" },
          ],
          methods: [
            { id: "mc1", visibility: "+", name: "getOrders()", type: "List<Order>" },
            { id: "mc2", visibility: "+", name: "upgradeTier()", type: "void" },
          ],
        },
      },
    ],
    edges: [
      {
        id: "eu-1",
        source: "uml-orderable",
        target: "uml-product",
        label: "«implements»",
        animated: false,
      },
      {
        id: "eu-2",
        source: "uml-order",
        target: "uml-product",
        label: "1 : * (has products)",
        animated: false,
      },
      {
        id: "eu-3",
        source: "uml-customer",
        target: "uml-order",
        label: "1 : * (places)",
        animated: false,
      },
    ],
  },

  {
    id: "erd-ecommerce",
    name: "E-Commerce Schema (ERD)",
    category: "erd",
    description: "Relational database schema: Users, Products, Categories, Orders, and Order Items",
    nodes: [
      {
        id: "tbl-users",
        type: "tableNode",
        position: { x: 50, y: 50 },
        data: {
          label: "users",
          tableName: "users",
          subtext: "User accounts & auth data",
          badge: "TABLE",
          colorTheme: "blue",
          columns: [
            { id: "u-id", name: "id", type: "UUID", isPk: true },
            { id: "u-email", name: "email", type: "VARCHAR(255)", isUnique: true },
            { id: "u-name", name: "full_name", type: "VARCHAR(120)" },
            { id: "u-role", name: "role", type: "VARCHAR(30)" },
            { id: "u-created", name: "created_at", type: "TIMESTAMP" },
          ],
        },
      },
      {
        id: "tbl-categories",
        type: "tableNode",
        position: { x: 420, y: 50 },
        data: {
          label: "categories",
          tableName: "categories",
          subtext: "Product categories hierarchy",
          badge: "TABLE",
          colorTheme: "amber",
          columns: [
            { id: "c-id", name: "id", type: "UUID", isPk: true },
            { id: "c-name", name: "name", type: "VARCHAR(100)" },
            { id: "c-slug", name: "slug", type: "VARCHAR(120)", isUnique: true },
            { id: "c-created", name: "created_at", type: "TIMESTAMP" },
          ],
        },
      },
      {
        id: "tbl-products",
        type: "tableNode",
        position: { x: 420, y: 320 },
        data: {
          label: "products",
          tableName: "products",
          subtext: "Inventory catalog items",
          badge: "TABLE",
          colorTheme: "emerald",
          columns: [
            { id: "p-id", name: "id", type: "UUID", isPk: true },
            { id: "p-cat-id", name: "category_id", type: "UUID", isFk: true },
            { id: "p-name", name: "title", type: "VARCHAR(200)" },
            { id: "p-price", name: "price", type: "NUMERIC(10,2)" },
            { id: "p-stock", name: "stock_quantity", type: "INTEGER" },
            { id: "p-created", name: "created_at", type: "TIMESTAMP" },
          ],
        },
      },
      {
        id: "tbl-orders",
        type: "tableNode",
        position: { x: 50, y: 350 },
        data: {
          label: "orders",
          tableName: "orders",
          subtext: "Customer order header",
          badge: "TABLE",
          colorTheme: "indigo",
          columns: [
            { id: "o-id", name: "id", type: "UUID", isPk: true },
            { id: "o-user-id", name: "user_id", type: "UUID", isFk: true },
            { id: "o-total", name: "total_amount", type: "NUMERIC(12,2)" },
            { id: "o-status", name: "status", type: "VARCHAR(50)" },
            { id: "o-created", name: "created_at", type: "TIMESTAMP" },
          ],
        },
      },
      {
        id: "tbl-order-items",
        type: "tableNode",
        position: { x: 420, y: 640 },
        data: {
          label: "order_items",
          tableName: "order_items",
          subtext: "Line items in an order",
          badge: "TABLE",
          colorTheme: "purple",
          columns: [
            { id: "oi-id", name: "id", type: "UUID", isPk: true },
            { id: "oi-order-id", name: "order_id", type: "UUID", isFk: true },
            { id: "oi-prod-id", name: "product_id", type: "UUID", isFk: true },
            { id: "oi-qty", name: "quantity", type: "INTEGER" },
            { id: "oi-unit-price", name: "unit_price", type: "NUMERIC(10,2)" },
          ],
        },
      },
    ],
    edges: [
      {
        id: "e-users-orders",
        source: "tbl-users",
        sourceHandle: "col-right-u-id",
        target: "tbl-orders",
        targetHandle: "col-left-o-user-id",
        label: "1 : N (user orders)",
        animated: false,
      },
      {
        id: "e-cat-prod",
        source: "tbl-categories",
        sourceHandle: "col-right-c-id",
        target: "tbl-products",
        targetHandle: "col-right-p-cat-id",
        label: "1 : N (category products)",
        animated: false,
      },
      {
        id: "e-order-items-order",
        source: "tbl-orders",
        sourceHandle: "col-right-o-id",
        target: "tbl-order-items",
        targetHandle: "col-left-oi-order-id",
        label: "1 : N (has items)",
        animated: false,
      },
      {
        id: "e-prod-items",
        source: "tbl-products",
        sourceHandle: "col-right-p-id",
        target: "tbl-order-items",
        targetHandle: "col-right-oi-prod-id",
        label: "1 : N (product in items)",
        animated: false,
      },
    ],
  },
  {
    id: "erd-devsolve",
    name: "DevSolve Platform Schema (ERD)",
    category: "erd",
    description: "Entities for problems, solutions, comments, tags, and profiles",
    nodes: [
      {
        id: "tbl-dev-users",
        type: "tableNode",
        position: { x: 50, y: 60 },
        data: {
          label: "users",
          tableName: "users",
          subtext: "Authentication credentials & identity",
          badge: "TABLE",
          colorTheme: "blue",
          columns: [
            { id: "du-id", name: "id", type: "UUID", isPk: true },
            { id: "du-sub", name: "keycloak_sub", type: "VARCHAR(255)", isUnique: true },
            { id: "du-uname", name: "username", type: "VARCHAR(60)", isUnique: true },
            { id: "du-email", name: "email", type: "VARCHAR(255)", isUnique: true },
            { id: "du-created", name: "created_at", type: "TIMESTAMP" },
          ],
        },
      },
      {
        id: "tbl-dev-profiles",
        type: "tableNode",
        position: { x: 50, y: 350 },
        data: {
          label: "user_profiles",
          tableName: "user_profiles",
          subtext: "Public bio, avatar, and social links",
          badge: "TABLE",
          colorTheme: "cyan",
          columns: [
            { id: "dp-id", name: "id", type: "UUID", isPk: true },
            { id: "dp-uid", name: "user_id", type: "UUID", isFk: true, isUnique: true },
            { id: "dp-bio", name: "bio", type: "TEXT", isNullable: true },
            { id: "dp-avatar", name: "avatar_url", type: "VARCHAR(500)", isNullable: true },
            { id: "dp-xp", name: "reputation_points", type: "INTEGER" },
          ],
        },
      },
      {
        id: "tbl-dev-problems",
        type: "tableNode",
        position: { x: 440, y: 60 },
        data: {
          label: "problems",
          tableName: "problems",
          subtext: "Bug reports and programming questions",
          badge: "TABLE",
          colorTheme: "emerald",
          columns: [
            { id: "dpr-id", name: "id", type: "UUID", isPk: true },
            { id: "dpr-author", name: "author_id", type: "UUID", isFk: true },
            { id: "dpr-title", name: "title", type: "VARCHAR(300)" },
            { id: "dpr-body", name: "description", type: "TEXT" },
            { id: "dpr-views", name: "view_count", type: "BIGINT" },
            { id: "dpr-created", name: "created_at", type: "TIMESTAMP" },
          ],
        },
      },
      {
        id: "tbl-dev-solutions",
        type: "tableNode",
        position: { x: 440, y: 380 },
        data: {
          label: "solutions",
          tableName: "solutions",
          subtext: "Answers and code showcases",
          badge: "TABLE",
          colorTheme: "purple",
          columns: [
            { id: "ds-id", name: "id", type: "UUID", isPk: true },
            { id: "ds-prob-id", name: "problem_id", type: "UUID", isFk: true },
            { id: "ds-author", name: "author_id", type: "UUID", isFk: true },
            { id: "ds-accepted", name: "is_accepted", type: "BOOLEAN" },
            { id: "ds-upvotes", name: "upvote_count", type: "INTEGER" },
            { id: "ds-created", name: "created_at", type: "TIMESTAMP" },
          ],
        },
      },
      {
        id: "tbl-dev-comments",
        type: "tableNode",
        position: { x: 830, y: 380 },
        data: {
          label: "comments",
          tableName: "comments",
          subtext: "Threaded discussions on solutions",
          badge: "TABLE",
          colorTheme: "amber",
          columns: [
            { id: "dc-id", name: "id", type: "UUID", isPk: true },
            { id: "dc-sol-id", name: "solution_id", type: "UUID", isFk: true },
            { id: "dc-author", name: "author_id", type: "UUID", isFk: true },
            { id: "dc-content", name: "content", type: "TEXT" },
            { id: "dc-created", name: "created_at", type: "TIMESTAMP" },
          ],
        },
      },
    ],
    edges: [
      {
        id: "e-dev-u-prof",
        source: "tbl-dev-users",
        sourceHandle: "col-left-du-id",
        target: "tbl-dev-profiles",
        targetHandle: "col-left-dp-uid",
        label: "1 : 1 (user profile)",
        animated: false,
      },
      {
        id: "e-dev-u-prob",
        source: "tbl-dev-users",
        sourceHandle: "col-right-du-id",
        target: "tbl-dev-problems",
        targetHandle: "col-left-dpr-author",
        label: "1 : N (created problems)",
        animated: false,
      },
      {
        id: "e-dev-prob-sol",
        source: "tbl-dev-problems",
        sourceHandle: "col-right-dpr-id",
        target: "tbl-dev-solutions",
        targetHandle: "col-left-ds-prob-id",
        label: "1 : N (solutions)",
        animated: false,
      },
      {
        id: "e-dev-sol-comm",
        source: "tbl-dev-solutions",
        sourceHandle: "col-right-ds-id",
        target: "tbl-dev-comments",
        targetHandle: "col-left-dc-sol-id",
        label: "1 : N (comments)",
        animated: false,
      },
    ],
  },

  {
    id: "system-architecture",
    name: "System Architecture",
    category: "architecture",
    description: "Standard web app stack: Client → API Gateway → Server → DB & Cache",
    nodes: [
      {
        id: "client-1",
        type: "clientNode",
        position: { x: 50, y: 150 },
        data: {
          label: "Next.js Web Client",
          subtext: "App Router & RTK Query",
          badge: "Frontend",
        },
      },
      {
        id: "gateway-1",
        type: "cloudNode",
        position: { x: 340, y: 150 },
        data: {
          label: "API Gateway / Proxy",
          subtext: "Auth verification & routing",
          badge: "Gateway",
        },
      },
      {
        id: "server-1",
        type: "serverNode",
        position: { x: 630, y: 150 },
        data: {
          label: "Spring Boot Core API",
          subtext: "Business logic & services",
          badge: "Backend",
        },
      },
      {
        id: "db-1",
        type: "databaseNode",
        position: { x: 920, y: 80 },
        data: {
          label: "PostgreSQL Database",
          subtext: "Primary persistent store",
          badge: "SQL DB",
        },
      },
      {
        id: "cache-1",
        type: "databaseNode",
        position: { x: 920, y: 220 },
        data: {
          label: "Redis Cache",
          subtext: "Session & query caching",
          badge: "Cache",
        },
      },
    ],
    edges: [
      {
        id: "e1",
        source: "client-1",
        target: "gateway-1",
        animated: true,
        label: "HTTPS / REST",
      },
      {
        id: "e2",
        source: "gateway-1",
        target: "server-1",
        animated: true,
        label: "Internal gRPC",
      },
      {
        id: "e3",
        source: "server-1",
        target: "db-1",
        label: "Read / Write",
      },
      {
        id: "e4",
        source: "server-1",
        target: "cache-1",
        label: "Cache Hit / Miss",
      },
    ],
  },
  {
    id: "auth-oauth-flow",
    name: "Auth & OAuth Flow",
    category: "architecture",
    description: "PKCE OIDC sequence: User → Better Auth → Keycloak → Protected API",
    nodes: [
      {
        id: "auth-client",
        type: "clientNode",
        position: { x: 50, y: 150 },
        data: {
          label: "Client App",
          subtext: "better-auth PKCE initiate",
          badge: "Client",
        },
      },
      {
        id: "auth-idp",
        type: "cloudNode",
        position: { x: 340, y: 70 },
        data: {
          label: "Keycloak OIDC Server",
          subtext: "Issues JWT access & refresh tokens",
          badge: "IdP",
        },
      },
      {
        id: "auth-decision",
        type: "decisionNode",
        position: { x: 340, y: 230 },
        data: {
          label: "Bearer token valid?",
          badge: "Verify JWT",
        },
      },
      {
        id: "auth-api",
        type: "serverNode",
        position: { x: 630, y: 230 },
        data: {
          label: "Protected API Service",
          subtext: "Returns user data & records",
          badge: "Resource Server",
        },
      },
    ],
    edges: [
      {
        id: "ea-1",
        source: "auth-client",
        target: "auth-idp",
        animated: true,
        label: "1. Login (PKCE)",
      },
      {
        id: "ea-2",
        source: "auth-idp",
        target: "auth-client",
        label: "2. Session & Token",
      },
      {
        id: "ea-3",
        source: "auth-client",
        target: "auth-decision",
        animated: true,
        label: "3. Request with Bearer",
      },
      {
        id: "ea-4",
        source: "auth-decision",
        target: "auth-api",
        label: "Yes: Allow request",
      },
    ],
  },
  {
    id: "microservices-pipeline",
    name: "Microservices & Queue",
    category: "architecture",
    description: "Event-driven workflow with Message Queue & Async Workers",
    nodes: [
      {
        id: "ms-client",
        type: "clientNode",
        position: { x: 50, y: 140 },
        data: {
          label: "Web / Mobile Client",
          subtext: "Uploads payload / dispatches job",
          badge: "Frontend",
        },
      },
      {
        id: "ms-api",
        type: "serverNode",
        position: { x: 330, y: 140 },
        data: {
          label: "Ingestion API",
          subtext: "Validates and enqueues task",
          badge: "API",
        },
      },
      {
        id: "ms-queue",
        type: "cloudNode",
        position: { x: 610, y: 140 },
        data: {
          label: "RabbitMQ / Kafka Queue",
          subtext: "Asynchronous task queue",
          badge: "Event Broker",
        },
      },
      {
        id: "ms-worker",
        type: "serverNode",
        position: { x: 890, y: 80 },
        data: {
          label: "Processing Worker",
          subtext: "Executes heavy background task",
          badge: "Worker",
        },
      },
      {
        id: "ms-db",
        type: "databaseNode",
        position: { x: 890, y: 220 },
        data: {
          label: "Storage & State",
          subtext: "Saves results & status",
          badge: "Database",
        },
      },
    ],
    edges: [
      {
        id: "em-1",
        source: "ms-client",
        target: "ms-api",
        animated: true,
        label: "POST /jobs",
      },
      {
        id: "em-2",
        source: "ms-api",
        target: "ms-queue",
        animated: true,
        label: "Publish Event",
      },
      {
        id: "em-3",
        source: "ms-queue",
        target: "ms-worker",
        animated: true,
        label: "Consume Event",
      },
      {
        id: "em-4",
        source: "ms-worker",
        target: "ms-db",
        label: "Persist Result",
      },
    ],
  },
];

