import { ReportItem, ReportDetail, RetestItem } from "./types";

export const MOCK_RETEST_HISTORY: RetestItem[] = [
  {
    id: "rt1",
    reportIdTitle: "RPT-2847: Broken Access Control",
    securityCategory: "Security Category: A01:2021",
    version: "v3.1",
    status: "PASSED",
    requestDate: "Oct 24, 2023",
    bountyBonus: "+15% Awarded",
  },
  {
    id: "rt2",
    reportIdTitle: "RPT-2847: Broken Access Control",
    securityCategory: "Security Category: A03:2021",
    version: "v1.2",
    status: "FAILED",
    requestDate: "Oct 21, 2023",
  },
];

// Initial mock dataset for reports matching the prompt specs
export const MOCK_REPORTS: ReportItem[] = [
  {
    id: "1",
    reportId: "RPT-2847",
    title: "Broken Access Control on User Profile API",
    program: "Global Enterprise VDP",
    avatarLetter: "B",
    type: "Bounty",
    severity: "HIGH",
    status: "ACCEPTED",
    bountyOrRep: "$1,500.00",
    isBountyHighlight: true,
    lastActivityDate: "Oct 24, 2023",
    lastActivityBadge: "STATUS UPDATE",
  },
  {
    id: "2",
    reportId: "RPT-2791",
    title: "Broken Access Control on Admin Panel",
    program: "GlobalRoute Pro",
    avatarLetter: "U",
    type: "Bounty",
    severity: "HIGH",
    status: "RESOLVED",
    bountyOrRep: "$1,500.00",
    isBountyHighlight: true,
    lastActivityDate: "Oct 20, 2023",
    lastActivityBadge: "PAYMENT ISSUED",
  },
  {
    id: "3",
    reportId: "RPT-2755",
    title: "Stored XSS in Comment Section",
    program: "CloudStore VDP",
    avatarLetter: "U",
    type: "Response",
    severity: "MEDIUM",
    status: "ACCEPTED",
    bountyOrRep: "Reputation",
    lastActivityDate: "Oct 15, 2023",
    lastActivityBadge: "STATUS UPDATE",
  },
  {
    id: "4",
    reportId: "RPT-2740",
    title: "Information Disclosure via Debug Header",
    program: "HealthSync Portal",
    avatarLetter: "U",
    type: "Bounty",
    severity: "LOW",
    status: "SUBMITTED",
    bountyOrRep: "$150.00",
    lastActivityDate: "Oct 12, 2023",
    lastActivityBadge: "RECEIVED",
  },
  {
    id: "5",
    reportId: "RPT-2702",
    title: "CSRF on Profile Settings",
    program: "CyberShield Dashboard",
    avatarLetter: "U",
    type: "Bounty",
    severity: "MEDIUM",
    status: "REJECTED",
    bountyOrRep: "$0.00",
    isBountyDim: true,
    lastActivityDate: "Oct 05, 2023",
    lastActivityBadge: "CLOSURE",
  },
  {
    id: "6",
    reportId: "RPT-2910",
    title: "IDOR in Invoices Export Endpoint",
    program: "Global Enterprise VDP",
    avatarLetter: "G",
    type: "Bounty",
    severity: "MEDIUM",
    status: "RETESTING",
    rawStatus: "RETESTING",
    bountyOrRep: "+$50.00 Bonus",
    isBountyHighlight: true,
    lastActivityDate: "Just now",
    lastActivityBadge: "RETEST REQUESTED",
    retestHistory: [
      {
        id: "ret_001",
        attemptNumber: 1,
        environment: "STAGING",
        targetEndpoint: "https://staging-api.example.com/v1/invoices",
        requestedAt: "2026-08-28T09:15:00",
        dueAt: "2026-09-11T09:15:00",
        requestedBy: { id: "org_001", name: "Global Enterprise Security" },
        requestNotes: "Remediation patch deployed to staging. Please re-verify IDOR vulnerability.",
        bountyReward: "50.00",
        completedAt: null,
        completedBy: null,
        verdict: null,
        resultNotes: null,
        attachmentIds: null,
      },
    ],
  },
];

/* MOCK_REPORT_DETAIL and MOCK_REJECTED_REPORT_DETAIL lived here and were
   served whenever /reports/{id} failed, and in place of every rejected report.
   Both screens now render the report the API returns, or say plainly that it
   could not be loaded, so the fixtures have no caller left. */
