import { ProgramItem } from "./programs/types";

export const MOCK_PROGRAMSss: ProgramItem[] = [
  {
    id: "1",
    companyName: "GitHub",
    companySlug: "github",
    logoUrl: "https://cdn.simpleicons.org/github/000000",
    logoBgColor: "bg-slate-100",
    type: "Bounty",
    status: "Open",
    isNew: true,
    isPrivate: false,
    title: "GitHub Platform Security Bounty",
    description: "Help secure GitHub.com, GitHub Enterprise Server, and core REST/GraphQL endpoints.",
    inScopeAssets: ["github.com", "api.github.com", "*.githubusercontent.com"],
    assetCategories: ["Web", "API"],
    rewardRange: "$555 - $50,000",
    rewardType: "bounty",
    totalBountyPaid: "$1,800,000",
    startDate: "Jan 1, 2026",
    endDate: "Dec 31, 2026",
    activeResearchers: 142,
    pocRequirements: [
      "Step-by-step reproduction guide",
      "Exact HTTP request/payload (Burp Suite export prefered)",
      "Video or screenshot proof demonstrating impact",
      "Affected endpoint and parameter details",
    ],
    inScopeTargets: ["github.com", "api.github.com", "*.githubusercontent.com"],
    outOfScopeTargets: ["gist.github.com", "Third-party GitHub Actions", "Internal corporate IT infrastructure"],
    bountyMatrix: [
      { severity: "Critical", payoutRange: "$20,000 – $50,000" },
      { severity: "High", payoutRange: "$5,000 – $20,000" },
      { severity: "Medium", payoutRange: "$1,500 – $5,000" },
      { severity: "Low", payoutRange: "$555 – $1,500" },
    ],
    rulesOfEngagement: [
      "Automated scanning allowed up to 5 req/sec only.",
      "Do not access, modify, or leak other users' repository data.",
      "Do not perform DoS/DDoS or resource exhaustion attacks.",
      "Submit one vulnerability per report.",
    ],
    exclusions: [
      "Self-XSS without clear exploitation path",
      "Missing security headers without demonstrated vulnerability",
      "Rate limiting issues on public endpoints",
    ],
    stats: {
      reportsSubmitted: 890,
      avgPayout: "$2,400",
      responseTime: "1 day",
    },
  },
  {
    id: "2",
    companyName: "Google",
    companySlug: "google",
    logoUrl: "https://cdn.simpleicons.org/google/4285F4",
    logoBgColor: "bg-blue-50",
    type: "Bounty",
    status: "Open",
    isNew: false,
    isPrivate: false,
    title: "Google Vulnerability Reward Program (VRP)",
    description: "Covers core Google web applications, Android services, and cloud platform interfaces.",
    inScopeAssets: ["*.google.com", "*.youtube.com", "android.googlesource.com"],
    assetCategories: ["Web", "Mobile", "API"],
    rewardRange: "$500 - $133,337",
    rewardType: "bounty",
    totalBountyPaid: "$12,000,000",
    startDate: "Feb 15, 2026",
    endDate: "Nov 30, 2026",
    activeResearchers: 310,
    pocRequirements: [
      "Working exploit POC or curl command",
      "Impact analysis detailing security boundary bypass",
      "Affected product version and build number",
    ],
    inScopeTargets: ["*.google.com", "*.youtube.com", "android.googlesource.com"],
    outOfScopeTargets: ["Acquired companies (< 6 months)", "Physical access to Google offices", "Social engineering"],
    bountyMatrix: [
      { severity: "Critical", payoutRange: "$31,337 – $133,337" },
      { severity: "High", payoutRange: "$13,337 – $31,337" },
      { severity: "Medium", payoutRange: "$3,133 – $13,337" },
      { severity: "Low", payoutRange: "$500 – $3,133" },
    ],
    rulesOfEngagement: [
      "Always use test accounts created for bug hunting.",
      "Do not attempt social engineering against Google personnel.",
      "Comply with local cyber laws during testing.",
    ],
    exclusions: [
      "SPF/DKIM/DMARC record configurations",
      "Clickjacking on pages with no sensitive state-changing actions",
    ],
    stats: {
      reportsSubmitted: 3100,
      avgPayout: "$4,200",
      responseTime: "12 hours",
    },
  },
  {
    id: "3",
    companyName: "Microsoft",
    companySlug: "microsoft",
    logoUrl: "https://cdn.simpleicons.org/microsoft/00A4EF",
    logoBgColor: "bg-slate-50",
    type: "Bounty",
    status: "Done",
    isNew: false,
    isPrivate: false,
    title: "Microsoft Azure & Office 365 Bounty",
    description: "Security response program covering Azure tenant boundaries and cloud management portals.",
    inScopeAssets: ["*.microsoft.com", "*.azure.com", "*.office.com"],
    assetCategories: ["Web", "Network", "API"],
    rewardRange: "$500 - $100,000",
    rewardType: "bounty",
    totalBountyPaid: "$4,500,000",
    startDate: "Jan 1, 2025",
    endDate: "Dec 31, 2025",
    activeResearchers: 89,
    pocRequirements: [
      "Text reproduction steps with screenshots",
      "Burp Suite request/response logs",
    ],
    inScopeTargets: ["*.microsoft.com", "*.azure.com", "*.office.com"],
    outOfScopeTargets: ["On-premise Active Directory software", "Xbox hardware"],
    bountyMatrix: [
      { severity: "Critical", payoutRange: "$30,000 – $100,000" },
      { severity: "High", payoutRange: "$10,000 – $30,000" },
      { severity: "Medium", payoutRange: "$3,000 – $10,000" },
      { severity: "Low", payoutRange: "$500 – $3,000" },
    ],
    rulesOfEngagement: [
      "Do not pivot between cloud tenants during authorization bypass testing.",
      "Report RCE immediately before executing commands beyond basic `whoami`.",
    ],
    exclusions: [
      "SSL/TLS best practices / weak ciphers",
      "Logout CSRF",
    ],
    stats: {
      reportsSubmitted: 1420,
      avgPayout: "$3,100",
      responseTime: "1 day",
    },
  },
  {
    id: "4",
    companyName: "Netflix",
    companySlug: "netflix",
    logoUrl: "https://cdn.simpleicons.org/netflix/E50914",
    logoBgColor: "bg-red-50",
    type: "Bounty",
    status: "Open",
    isNew: true,
    isPrivate: false,
    title: "Netflix Streaming & Mobile Security",
    description: "In-scope: Netflix streaming web apps, iOS/Android mobile clients, and partner APIs.",
    inScopeAssets: ["*.netflix.com", "api.netflix.com", "Netflix Mobile Apps"],
    assetCategories: ["Web", "Mobile", "API"],
    rewardRange: "$100 - $25,000",
    rewardType: "bounty",
    totalBountyPaid: "$850,000",
    startDate: "Mar 1, 2026",
    endDate: "Dec 31, 2026",
    activeResearchers: 64,
    pocRequirements: [
      "Mobile APK/IPA decompilation logs if applicable",
      "API payload analysis",
    ],
    inScopeTargets: ["*.netflix.com", "api.netflix.com", "Netflix Mobile Apps"],
    outOfScopeTargets: ["DRM / Content decryption algorithms", "Open Source Fast.com repository"],
    bountyMatrix: [
      { severity: "Critical", payoutRange: "$10,000 – $25,000" },
      { severity: "High", payoutRange: "$3,500 – $10,000" },
      { severity: "Medium", payoutRange: "$1,000 – $3,500" },
      { severity: "Low", payoutRange: "$100 – $1,000" },
    ],
    rulesOfEngagement: [
      "Do not attempt streaming session hijacking on live users.",
      "Limit automated tools to 3 requests per second.",
    ],
    exclusions: [
      "Geoblocking bypasses without backend account takeover",
      "User enumeration via forgot password form",
    ],
    stats: {
      reportsSubmitted: 512,
      avgPayout: "$1,850",
      responseTime: "18 hours",
    },
  },
  {
    id: "5",
    companyName: "Shopify",
    companySlug: "shopify",
    logoUrl: "https://cdn.simpleicons.org/shopify/7AB55C",
    logoBgColor: "bg-emerald-50",
    type: "Bounty",
    status: "Open",
    isNew: false,
    isPrivate: false,
    title: "Shopify Core Admin & Merchant Checkout",
    description: "Securing Shopify merchant dashboard, checkout infrastructure, and GraphQL gateway.",
    inScopeAssets: ["*.myshopify.com", "admin.shopify.com", "checkout.shopify.com"],
    assetCategories: ["Web", "API"],
    rewardRange: "$500 - $50,000",
    rewardType: "bounty",
    totalBountyPaid: "$3,100,000",
    startDate: "Jan 10, 2026",
    endDate: "Dec 10, 2026",
    activeResearchers: 180,
    pocRequirements: [
      "GraphQL query/mutation payloads",
      "Merchant store reproduction steps",
    ],
    inScopeTargets: ["*.myshopify.com", "admin.shopify.com", "checkout.shopify.com"],
    outOfScopeTargets: ["Third-party app store applications", "Theme developer custom JS"],
    bountyMatrix: [
      { severity: "Critical", payoutRange: "$15,000 – $50,000" },
      { severity: "High", payoutRange: "$5,000 – $15,000" },
      { severity: "Medium", payoutRange: "$1,500 – $5,000" },
      { severity: "Low", payoutRange: "$500 – $1,500" },
    ],
    rulesOfEngagement: [
      "Use test partner stores only.",
      "Do not perform transactions using stolen credit cards.",
    ],
    exclusions: [
      "Broken link hijacking",
      "CSV injection without impact proof",
    ],
    stats: {
      reportsSubmitted: 1620,
      avgPayout: "$2,100",
      responseTime: "1 day",
    },
  },
  {
    id: "6",
    companyName: "Uber",
    companySlug: "uber",
    logoUrl: "https://cdn.simpleicons.org/uber/000000",
    logoBgColor: "bg-gray-100",
    type: "Bounty",
    status: "Open",
    isNew: false,
    isPrivate: false,
    title: "Uber Rider & Driver Application Security",
    description: "Assessing Uber's rider, driver, and UberEats mobile applications alongside ride gateways.",
    inScopeAssets: ["*.uber.com", "rider.uber.com", "Uber iOS & Android Apps"],
    assetCategories: ["Mobile", "API", "Web"],
    rewardRange: "$500 - $35,000",
    rewardType: "bounty",
    totalBountyPaid: "$2,900,000",
    startDate: "Feb 1, 2026",
    endDate: "Dec 31, 2026",
    activeResearchers: 120,
    pocRequirements: [
      "Mobile request interception logs (Mitmproxy/Charles)",
      "Step-by-step account flow details",
    ],
    inScopeTargets: ["*.uber.com", "rider.uber.com", "Uber iOS & Android Apps"],
    outOfScopeTargets: ["Third-party driver hardware units", "Jump Bikes IoT firmware"],
    bountyMatrix: [
      { severity: "Critical", payoutRange: "$12,000 – $35,000" },
      { severity: "High", payoutRange: "$4,000 – $12,000" },
      { severity: "Medium", payoutRange: "$1,200 – $4,000" },
      { severity: "Low", payoutRange: "$500 – $1,200" },
    ],
    rulesOfEngagement: [
      "Do not cancel real trips or disrupt active drivers.",
      "Test using personal accounts created specifically for researchers.",
    ],
    exclusions: [
      "GPS spoofing issues inherent to device hardware",
      "Software version disclosure",
    ],
    stats: {
      reportsSubmitted: 1400,
      avgPayout: "$2,800",
      responseTime: "2 days",
    },
  },
  {
    id: "7",
    companyName: "Cloudflare",
    companySlug: "cloudflare",
    logoUrl: "https://cdn.simpleicons.org/cloudflare/F38020",
    logoBgColor: "bg-amber-50",
    type: "Bounty",
    status: "Open",
    isNew: false,
    isPrivate: false,
    title: "Cloudflare Edge & DNS Infrastructure",
    description: "Testing Cloudflare CDN edge nodes, authoritative DNS servers, and customer portal APIs.",
    inScopeAssets: ["*.cloudflare.com", "dash.cloudflare.com", "DNS Edge Nodes"],
    assetCategories: ["Network", "API", "Web"],
    rewardRange: "$500 - $20,000",
    rewardType: "bounty",
    totalBountyPaid: "$1,100,000",
    startDate: "Jan 1, 2026",
    endDate: "Dec 31, 2026",
    activeResearchers: 95,
    pocRequirements: [
      "HTTP request header manipulation logs",
      "Edge bypass script or proof of concept",
    ],
    inScopeTargets: ["*.cloudflare.com", "dash.cloudflare.com", "DNS Edge Nodes"],
    outOfScopeTargets: ["Customer websites hosted behind Cloudflare", "WAF rule bypasses without underlying platform vulnerability"],
    bountyMatrix: [
      { severity: "Critical", payoutRange: "$8,000 – $20,000" },
      { severity: "High", payoutRange: "$3,000 – $8,000" },
      { severity: "Medium", payoutRange: "$1,000 – $3,000" },
      { severity: "Low", payoutRange: "$500 – $1,000" },
    ],
    rulesOfEngagement: [
      "Do not trigger global CDN node outages.",
      "Respect bandwidth limit tests.",
    ],
    exclusions: [
      "Origin IP discovery without administrative exposure",
      "Any issue on customer domain hosted on Cloudflare",
    ],
    stats: {
      reportsSubmitted: 610,
      avgPayout: "$2,300",
      responseTime: "18 hours",
    },
  },
  {
    id: "8",
    companyName: "OpenAI",
    companySlug: "openai",
    logoUrl: "https://cdn.simpleicons.org/openai/412991",
    logoBgColor: "bg-purple-50",
    type: "Bounty",
    status: "Open",
    isNew: true,
    isPrivate: false,
    title: "OpenAI ChatGPT & Platform Security",
    description: "Focusing on ChatGPT web UI, API keys management, and developer platform authorization.",
    inScopeAssets: ["chatgpt.com", "platform.openai.com", "api.openai.com"],
    assetCategories: ["Web", "API"],
    rewardRange: "$200 - $20,000",
    rewardType: "bounty",
    totalBountyPaid: "$620,000",
    startDate: "Apr 1, 2026",
    endDate: "Dec 31, 2026",
    activeResearchers: 210,
    pocRequirements: [
      "Exact API endpoints and JSON bodies",
      "Account privilege escalation reproduction steps",
    ],
    inScopeTargets: ["chatgpt.com", "platform.openai.com", "api.openai.com"],
    outOfScopeTargets: ["Model Jailbreaks / Prompt Injection without infrastructure impact", "Hallucinations"],
    bountyMatrix: [
      { severity: "Critical", payoutRange: "$6,500 – $20,000" },
      { severity: "High", payoutRange: "$2,500 – $6,500" },
      { severity: "Medium", payoutRange: "$600 – $2,500" },
      { severity: "Low", payoutRange: "$200 – $600" },
    ],
    rulesOfEngagement: [
      "Do not use prompt injection alone unless it leaks platform service tokens.",
      "Limit automated testing rate to 5 requests per second.",
    ],
    exclusions: [
      "Safety model bypasses (report via model safety form instead)",
      "Model output correctness issues",
    ],
    stats: {
      reportsSubmitted: 780,
      avgPayout: "$2,200",
      responseTime: "12 hours",
    },
  },
  {
    id: "9",
    companyName: "Stripe",
    companySlug: "stripe",
    logoUrl: "https://cdn.simpleicons.org/stripe/635BFF",
    logoBgColor: "bg-indigo-50",
    type: "Bounty",
    status: "Open",
    isNew: false,
    isPrivate: false,
    title: "Stripe Payment Gateway & Connect API",
    description: "Focusing on payment processing boundaries, Webhooks execution, and API token isolation.",
    inScopeAssets: ["*.stripe.com", "api.stripe.com", "js.stripe.com"],
    assetCategories: ["Web", "API"],
    rewardRange: "$500 - $40,000",
    rewardType: "bounty",
    totalBountyPaid: "$2,200,000",
    startDate: "Jan 1, 2026",
    endDate: "Dec 31, 2026",
    activeResearchers: 150,
    pocRequirements: [
      "Stripe CLI webhook logs",
      "API request traces and authorization headers",
    ],
    inScopeTargets: ["*.stripe.com", "api.stripe.com", "js.stripe.com"],
    outOfScopeTargets: ["Stripe Terminal physical hardware attack vectors"],
    bountyMatrix: [
      { severity: "Critical", payoutRange: "$15,000 – $40,000" },
      { severity: "High", payoutRange: "$5,000 – $15,000" },
      { severity: "Medium", payoutRange: "$1,500 – $5,000" },
      { severity: "Low", payoutRange: "$500 – $1,500" },
    ],
    rulesOfEngagement: [
      "Always test in Sandbox / Test mode.",
      "Do not process real financial transactions using stolen tokens.",
    ],
    exclusions: [
      "Testing live card numbers",
      "Reflected XSS on outdated sandbox webhooks",
    ],
    stats: {
      reportsSubmitted: 730,
      avgPayout: "$3,100",
      responseTime: "12 hours",
    },
  },
  {
    id: "10",
    companyName: "Twilio",
    companySlug: "twilio",
    logoUrl: "https://cdn.simpleicons.org/twilio/F22F46",
    logoBgColor: "bg-red-50",
    type: "Response",
    status: "Open",
    isNew: false,
    isPrivate: false,
    title: "Twilio Vulnerability Disclosure Program",
    description: "Coordinated disclosure program covering Twilio Voice, SMS, SendGrid, and Segment APIs.",
    inScopeAssets: ["*.twilio.com", "*.sendgrid.com", "api.segment.io"],
    assetCategories: ["API", "Web"],
    rewardRange: "+20 - +100 pts",
    rewardType: "points",
    startDate: "May 1, 2026",
    endDate: "Dec 31, 2026",
    activeResearchers: 45,
    pocRequirements: [
      "Step-by-step impact breakdown",
      "API payload details",
    ],
    inScopeTargets: ["*.twilio.com", "*.sendgrid.com", "api.segment.io"],
    outOfScopeTargets: ["Telecommunication network provider vulnerabilities"],
    bountyMatrix: [
      { severity: "Critical", payoutRange: "100 points" },
      { severity: "High", payoutRange: "60 points" },
      { severity: "Medium", payoutRange: "40 points" },
      { severity: "Low", payoutRange: "20 points" },
    ],
    rulesOfEngagement: [
      "This is a non-monetary disclosure program.",
      "Respect account isolation boundaries.",
    ],
    exclusions: [
      "SMS toll fraud scenarios without software flaw",
      "Sender ID spoofing on cellular carriers",
    ],
    stats: {
      reportsSubmitted: 210,
      responseTime: "2 days",
    },
  },
];